### ISSUE TITLE
DafnyRuntime not compatible with .NET frameworks earlier than .NET 6.0

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#2779]
Result of being too restrictive in the DafnyRuntime.csproj configuration. Blocks adoption by projects that need to support earlier versions such as https://github.com/aws/aws-encryption-sdk-dafny.

**Comment by robin-aws** [comment]
Abusing `release-blocker` a bit just to make sure this is fixed (if possible) before the next release, which should happen very soon to address #2776.

**Comment by atomb** [comment]
I believe this was resolved by #2604. It uses a slightly different set of target frameworks than https://github.com/aws/aws-encryption-sdk-dafny, but my understanding is that it's a compatible set.

**Comment by texastony** [comment]
Was this closed on the PR merge or a release of the Runtime to nuget?
It would appear on the PR merge, as Nuget is still restricting: https://www.nuget.org/packages/DafnyRuntime#supportedframeworks-body-tab

**Comment by robin-aws** [comment]
On the PR merge, but we are already working towards getting a release out in a matter of days.

**Comment by texastony** [comment]
On November 26th, 
I pulled DafnyRuntime  @ `3.9.1.41027-nightly-2022-11-26-2e0b8a9` 
into a project and attempted a build with following .csproj settings:
```
<LangVersion>7.3</LangVersion>
<TargetFrameworks>netstandard2.1;net452</TargetFrameworks>
```

Running `dotnet build` resulted in Error, 
due to the implicit use of `System.Globalization` @ 4.3.0 by `DafnyRuntime`,
which does not support C# 7.3.

Sample Error:
```
  STD.GlobalUsings.g.cs(2, 1): [CS8370] Feature 'global using directive' is not available in C# 7.3. Please use language version 10.0 or greater.
 ```

I can do more digging, but it appears that `DafnyRuntime` does not support C# @ 7.3.

**Comment by texastony** [comment]
Using C# @ 10, I encountered another error,
though it MAY not be from DafnyRuntime:

```
net452/STD.GlobalUsings.g.cs(6,33): error CS0234: The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)
```

I can work around this by adding `System.Net.Http` as a dependency:
```
<PackageReference Include="System.Net.Http" Version="4.3.4" />
```

With that, my project builds for Frameworks `netstandard2.1;net452`.

**Comment by texastony** [comment]
Ahh... I a may have been too quick to speak.
It turns out that I had:
```
    <ImplicitUsings>enable</ImplicitUsings>
```
in my `csproj`. 
If I disable that, then I can compile with 7.3 and no dependency on `System.Net.Http` or `System.Globalization`.
