### ISSUE TITLE
Rust backend broken in master, not detected by CI

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#5200]
### Dafny version

master

### Code to produce this issue

```dafny
method Main() {
    print "Hello, World! Best, Dafny\n";
    var x := 14;
    print "x is ", x, "\n";
    var y := false;
    print "y is ", y, "\n";
}
```

### Command to run and resulting output

```code
% dafny run -t:rs Hello.dfy

Dafny program verifier finished with 0 verified, 0 errors
error[E0446]: private type `Sequence<T>` in public interface
   --> runtime/src/lib.rs:51:5
    |
51  | /     pub fn dafny_sequence_to_vec<T, X>(s: &Sequence<T>, elem_converter: fn(&T) -> X) -> Vec<X>
52  | |       where T: Clone
    | |____________________^ can't leak private type
...
125 |   enum Sequence<T>
    |   ---------------- `Sequence<T>` declared as private

error[E0446]: private type `Sequence<T>` in public interface
   --> runtime/src/lib.rs:60:5
    |
60  | /     pub fn vec_to_dafny_sequence<T, X>(array: &Vec<X>, elem_converter: fn(&X) -> T) -> Rc<Sequence<T>>
61  | |       where T: Clone
    | |____________________^ can't leak private type
...
125 |   enum Sequence<T>
    |   ---------------- `Sequence<T>` declared as private

error[E0446]: private type `Sequence<char>` in public interface
   --> runtime/src/lib.rs:100:9
    |
100 |         pub fn string_to_dafny_string(s: &str) -> Rc<Sequence<char>> {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
...
125 | enum Sequence<T>
    | ---------------- `Sequence<char>` declared as private

error[E0446]: private type `Sequence<char>` in public interface
   --> runtime/src/lib.rs:103:9
    |
103 |         pub fn dafny_string_to_string(s: &Rc<Sequence<char>>) -> String {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
...
125 | enum Sequence<T>
    | ---------------- `Sequence<char>` declared as private

error[E0446]: private type `Sequence<u16>` in public interface
   --> runtime/src/lib.rs:113:9
    |
113 |         pub fn string_to_dafny_string(s: &str) -> Rc<Sequence<u16>> {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
...
125 | enum Sequence<T>
    | ---------------- `Sequence<u16>` declared as private

error[E0446]: private type `Sequence<u16>` in public interface
   --> runtime/src/lib.rs:116:9
    |
116 |         pub fn dafny_string_to_string(s: &Rc<Sequence<u16>>) -> String {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
...
125 | enum Sequence<T>
    | ---------------- `Sequence<u16>` declared as private

For more information about this error, try `rustc --explain E0446`.
error: could not compile `dafny_runtime` (lib) due to 6 previous errors
Error while compiling Rust files. Process exited with exit code 101
```

### What happened?

Root cause seems to be the Rust runtime (`lib.rs`) is invalid after recent changes. But it's a mystery to me why CI is not detecting this, given all of the `%testDafnyForEachCompiler` tests should be running on the Rust compiler and not a single one should pass on Rust.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
Just figured this out: it's a different in `rustc` versions between CI and my local setup (and others). The errors above don't show up any more when I upgrade to 1.76.0.

This just boils down to another case of #1983, although it's also straightforward to fix the offending code in the runtime to not care as much.
