### ISSUE TITLE
Dafny 3.4.2 Requires C# 8

### ISSUE THREAD

**Issue by texastony** [dafny-lang/dafny#1873]
While testing Dafny 3.4.2 on our library, which targets C#, we encountered the following error when testing in C#:

```
src/redacted/redacted/redacted/redacted/Source/obj/Debug/netstandard2.0/GeneratedFromDafny.cs(11926,20): error CS8370: Feature 'recursive patterns' is not available in C# 7.3. Please use language version 8.0 or greater.
```

There is no call out in the release notes for 3.4.2 that C#8 will now be required. 

Our library works fine on Dafny 3.4.1. 

Thank you!

**Comment by fabiomadge** [comment]
The change was part of #1780 and there is no real need for it, so we can just replace the offending line with something backwards compatible.
