### ISSUE TITLE
[REGRESSION] Nested set comprehension fails to compile for Rust

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#6357]
### Dafny version

4.11

### Code to produce this issue

```dafny
const SomeMaps := {map["a" := "b"]}
const OhNo := set x <- (set m <- SomeMaps :: m)
```

### Command to run and resulting output

```code
% dafny build -t:rs Scratch.dfy --enforce-determinism

Dafny program verifier finished with 0 verified, 0 errors
error[E0282]: type annotations needed
  --> src/Scratch.rs:39:24
   |
39 |                 }))()).iter().cloned() {
   |                        ^^^^ cannot infer type

For more information about this error, try `rustc --explain E0282`.
error: could not compile `Scratch` (lib) due to 1 previous error
Error while compiling Rust files. Process exited with exit code 101
```

### What happened?

Regression, works correctly on Dafny 4.10.

Caused by https://github.com/dafny-lang/dafny/pull/6143. Looks to be triggered by the extra wrapping of lambdas by `LambdaWrapRc` somehow.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
Fixed by https://github.com/dafny-lang/dafny/pull/6358
